---
title: "Using EPIC in R"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
vignette: >
  %\VignetteIndexEntry{UsingEPICinR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8} 
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

options(rmarkdown.html_vignette.check_title = FALSE)
```

## 1 Installation

...

```{r, eval=TRUE, echo=FALSE}
library(htmltools)
includeCSS(system.file("html/section-3/style-table.css", package = "epicUS"))
rawHTML <- paste(readLines(system.file("html/section-3/set-inputs.html", package = "epicUS")), collapse="\n")
HTML(rawHTML)
```

...

```{r, eval=TRUE, echo=FALSE}
library(htmltools)
includeCSS(system.file("html/section-3/style-table.css", package = "epicUS"))
rawHTML <- paste(readLines(system.file("html/section-3/main-results.html", package = "epicUS")), collapse="\n")
HTML(rawHTML)
```

...

```{r, eval=TRUE, echo=FALSE}
library(htmltools)
includeCSS(system.file("html/section-3/style-table.css", package = "epicUS"))
rawHTML <- paste(readLines(system.file("html/section-3/ex-results.htm", package = "epicUS")), collapse="\n")
HTML(rawHTML)
```

...

```{r, eval=TRUE, echo=FALSE}
library(htmltools)
includeCSS(system.file("html/section-3/style-mini-table.css", package = "epicUS"))
rawHTML <- paste(readLines(system.file("html/section-3/record_mode.html", package = "epicUS")), collapse="\n")
HTML(rawHTML)
```

...

```{r, eval=TRUE, echo=FALSE}
library(htmltools)
includeCSS(system.file("html/section-3/style-table.css", package = "epicUS"))
rawHTML <- paste(readLines(system.file("html/section-3/event-matrix-cols.html", package = "epicUS")), collapse="\n")
HTML(rawHTML)
```

...

```{r, eval=TRUE, echo=FALSE}
library(htmltools)
includeCSS(system.file("html/section-3/style-mini-table.css", package = "epicUS"))
rawHTML <- paste(readLines(system.file("html/section-3/events.html", package = "epicUS")), collapse="\n")
HTML(rawHTML)
```

...
